name: push
on:
  push:


jobs:
  version:
    uses: TresSims/auto-devops/.github/workflows/version.yml@1-version-pipeline
  docker:
    permissions:
      packages: write
      contents: read
    uses: TresSims/auto-devops/.github/workflows/docker.yml@1-version-pipeline
    needs: version
    with:
      tags: ${{needs.version.outputs.tags}}
