name: push
on:
  push:


jobs:
  version:
    uses: TresSims/auto-devops/.github/workflows/version.yml@1-version-pipeline
  build:
    uses: TresSims/auto-devops/.github/workflows/docker.yml@1-version-pipeline
