name: push
on:
  push:
    branches:
      - main


jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create Version
        id: release-version
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          version_format: "${major}.${minor}.${patch}"
      - name: Create version releases
        if: inputs.create-release
        uses: rickstaa/action-create-tag@v1
        with:
          tag: steps.release-version.outputs.version
      - name: Create latest releases
        if: inputs.create-release
        uses: rickstaa/action-create-tag@v1
        with:
          tag: latest
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Change case for image
        id: case
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{github.repository_owner}}/${{github.event.repository.name}}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{steps.case.outputs.lowercase}}:latest
            ghcr.io/${{steps.case.outputs.lowercase}}:${{steps.semver-tag.outputs.version}}

    








