name: push
on:
  push:


jobs:
  version:
    uses: TresSims/auto-devops/.github/workflows/version.yml@1-version-pipeline
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Change case for image
        id: case
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{github.repository_owner}}/${{github.event.repository.name}}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{steps.case.outputs.lowercase}}:latest
            ghcr.io/${{steps.case.outputs.lowercase}}:${{steps.semver-tag.outputs.version}}

